#!/bin/bash
# Usage: ./run 1 [target]

FILE="makefile$1"
shift # remove the '1' from the arguments

if [ -f "$FILE" ]; then
    make -f "$FILE" "$@"
else
    echo "Error: $FILE not found."
fi

# Use it like this: 
# ./run 1 (Runs Makefile1)
# ./run 2 clean (Runs the 'clean' target inside Makefile2)