#!/bin/bash
# Check if a number was provided
if [ -z "$1" ]; then
    echo "Usage: ./run [number] [target]"
    exit 1
fi

MAKE_FILE="makefile$1"
shift 

# Run make, passing the remaining arguments
make -f "$MAKE_FILE" "$@"